name: build and publish dockerfile
on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: "miguelmerlin"
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/miguelmerlin/polyglot_backend:${{ github.sha }}
          ghcr.io/miguelmerlin/polyglot_backend:latest